#include "Utf8.h"

// Generated by https://github.com/bretcope/mot/blob/master/ToUpperLowerGen.linq
// DO NOT hand-edit this file.
// It is generated using the .NET rules for invariant culture.

char32_t Utf8::ToUpper(char32_t ch)
{
    int32_t diff = 0;
    if (ch >= 97u && ch <= 122u) // ['a', 'z']
    {
        diff = 32;
        goto APPLY_DIFF;
    }

    if (ch >= 224u && ch <= 65370u) // ['à', 'ｚ']
    {
        if (ch <= 961u) // ['à', 'ρ']
        {
            if (ch <= 543u) // ['à', 'ȟ']
            {
                if (ch <= 414u) // ['à', 'ƞ']
                {
                    if (ch <= 382u) // ['à', 'ž']
                    {
                        if (ch <= 303u) // ['à', 'į']
                        {
                            if (ch <= 254u) // ['à', 'þ']
                            {
                                if (ch <= 246u) // ['à', 'ö']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['à', 'ö']
                                else if (ch >= 248u) // ['ø', 'þ']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['ø', 'þ']
                            } // ['à', 'þ']
                            else if (ch >= 255u) // ['ÿ', 'į']
                            {
                                if (ch <= 255u) // ['ÿ', 'ÿ']
                                {
                                    diff = -121;
                                    goto APPLY_DIFF;
                                } // ['ÿ', 'ÿ']
                                else if (ch >= 256u) // ['Ā', 'į']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ā', 'į']
                            } // ['ÿ', 'į']
                        } // ['à', 'į']
                        else if (ch >= 306u) // ['Ĳ', 'ž']
                        {
                            if (ch <= 328u) // ['Ĳ', 'ň']
                            {
                                if (ch <= 311u) // ['Ĳ', 'ķ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ĳ', 'ķ']
                                else if (ch >= 313u) // ['Ĺ', 'ň']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ĺ', 'ň']
                            } // ['Ĳ', 'ň']
                            else if (ch >= 330u) // ['Ŋ', 'ž']
                            {
                                if (ch <= 375u) // ['Ŋ', 'ŷ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ŋ', 'ŷ']
                                else if (ch >= 377u) // ['Ź', 'ž']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ź', 'ž']
                            } // ['Ŋ', 'ž']
                        } // ['Ĳ', 'ž']
                    } // ['à', 'ž']
                    else if (ch >= 384u) // ['ƀ', 'ƞ']
                    {
                        if (ch <= 396u) // ['ƀ', 'ƌ']
                        {
                            if (ch <= 389u) // ['ƀ', 'ƅ']
                            {
                                if (ch <= 384u) // ['ƀ', 'ƀ']
                                {
                                    diff = -195;
                                    goto APPLY_DIFF;
                                } // ['ƀ', 'ƀ']
                                else if (ch >= 386u) // ['Ƃ', 'ƅ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƃ', 'ƅ']
                            } // ['ƀ', 'ƅ']
                            else if (ch >= 391u) // ['Ƈ', 'ƌ']
                            {
                                if (ch <= 392u) // ['Ƈ', 'ƈ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƈ', 'ƈ']
                                else if (ch >= 395u) // ['Ƌ', 'ƌ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƌ', 'ƌ']
                            } // ['Ƈ', 'ƌ']
                        } // ['ƀ', 'ƌ']
                        else if (ch >= 401u) // ['Ƒ', 'ƞ']
                        {
                            if (ch <= 405u) // ['Ƒ', 'ƕ']
                            {
                                if (ch <= 402u) // ['Ƒ', 'ƒ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƒ', 'ƒ']
                                else if (ch >= 405u) // ['ƕ', 'ƕ']
                                {
                                    diff = -97;
                                    goto APPLY_DIFF;
                                } // ['ƕ', 'ƕ']
                            } // ['Ƒ', 'ƕ']
                            else if (ch >= 408u) // ['Ƙ', 'ƞ']
                            {
                                if (ch <= 409u) // ['Ƙ', 'ƙ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƙ', 'ƙ']
                                else if (ch >= 410u) // ['ƚ', 'ƞ']
                                {
                                    if (ch <= 410u) // ['ƚ', 'ƚ']
                                    {
                                        diff = -163;
                                        goto APPLY_DIFF;
                                    } // ['ƚ', 'ƚ']
                                    else if (ch >= 414u) // ['ƞ', 'ƞ']
                                    {
                                        diff = -130;
                                        goto APPLY_DIFF;
                                    } // ['ƞ', 'ƞ']
                                } // ['ƚ', 'ƞ']
                            } // ['Ƙ', 'ƞ']
                        } // ['Ƒ', 'ƞ']
                    } // ['ƀ', 'ƞ']
                } // ['à', 'ƞ']
                else if (ch >= 416u) // ['Ơ', 'ȟ']
                {
                    if (ch <= 447u) // ['Ơ', 'ƿ']
                    {
                        if (ch <= 432u) // ['Ơ', 'ư']
                        {
                            if (ch <= 424u) // ['Ơ', 'ƨ']
                            {
                                if (ch <= 421u) // ['Ơ', 'ƥ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ơ', 'ƥ']
                                else if (ch >= 423u) // ['Ƨ', 'ƨ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƨ', 'ƨ']
                            } // ['Ơ', 'ƨ']
                            else if (ch >= 428u) // ['Ƭ', 'ư']
                            {
                                if (ch <= 429u) // ['Ƭ', 'ƭ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƭ', 'ƭ']
                                else if (ch >= 431u) // ['Ư', 'ư']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ư', 'ư']
                            } // ['Ƭ', 'ư']
                        } // ['Ơ', 'ư']
                        else if (ch >= 435u) // ['Ƴ', 'ƿ']
                        {
                            if (ch <= 441u) // ['Ƴ', 'ƹ']
                            {
                                if (ch <= 438u) // ['Ƴ', 'ƶ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƴ', 'ƶ']
                                else if (ch >= 440u) // ['Ƹ', 'ƹ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƹ', 'ƹ']
                            } // ['Ƴ', 'ƹ']
                            else if (ch >= 444u) // ['Ƽ', 'ƿ']
                            {
                                if (ch <= 445u) // ['Ƽ', 'ƽ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƽ', 'ƽ']
                                else if (ch >= 447u) // ['ƿ', 'ƿ']
                                {
                                    diff = -56;
                                    goto APPLY_DIFF;
                                } // ['ƿ', 'ƿ']
                            } // ['Ƽ', 'ƿ']
                        } // ['Ƴ', 'ƿ']
                    } // ['Ơ', 'ƿ']
                    else if (ch >= 454u) // ['ǆ', 'ȟ']
                    {
                        if (ch <= 476u) // ['ǆ', 'ǜ']
                        {
                            if (ch <= 457u) // ['ǆ', 'ǉ']
                            {
                                if (ch <= 454u) // ['ǆ', 'ǆ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['ǆ', 'ǆ']
                                else if (ch >= 457u) // ['ǉ', 'ǉ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['ǉ', 'ǉ']
                            } // ['ǆ', 'ǉ']
                            else if (ch >= 460u) // ['ǌ', 'ǜ']
                            {
                                if (ch <= 460u) // ['ǌ', 'ǌ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['ǌ', 'ǌ']
                                else if (ch >= 461u) // ['Ǎ', 'ǜ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ǎ', 'ǜ']
                            } // ['ǌ', 'ǜ']
                        } // ['ǆ', 'ǜ']
                        else if (ch >= 477u) // ['ǝ', 'ȟ']
                        {
                            if (ch <= 495u) // ['ǝ', 'ǯ']
                            {
                                if (ch <= 477u) // ['ǝ', 'ǝ']
                                {
                                    diff = 79;
                                    goto APPLY_DIFF;
                                } // ['ǝ', 'ǝ']
                                else if (ch >= 478u) // ['Ǟ', 'ǯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ǟ', 'ǯ']
                            } // ['ǝ', 'ǯ']
                            else if (ch >= 499u) // ['ǳ', 'ȟ']
                            {
                                if (ch <= 499u) // ['ǳ', 'ǳ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['ǳ', 'ǳ']
                                else if (ch >= 500u) // ['Ǵ', 'ȟ']
                                {
                                    if (ch <= 501u) // ['Ǵ', 'ǵ']
                                    {
                                        goto UPPERCASE_IS_EVEN;
                                    } // ['Ǵ', 'ǵ']
                                    else if (ch >= 504u) // ['Ǹ', 'ȟ']
                                    {
                                        goto UPPERCASE_IS_EVEN;
                                    } // ['Ǹ', 'ȟ']
                                } // ['Ǵ', 'ȟ']
                            } // ['ǳ', 'ȟ']
                        } // ['ǝ', 'ȟ']
                    } // ['ǆ', 'ȟ']
                } // ['Ơ', 'ȟ']
            } // ['à', 'ȟ']
            else if (ch >= 546u) // ['Ȣ', 'ρ']
            {
                if (ch <= 623u) // ['Ȣ', 'ɯ']
                {
                    if (ch <= 596u) // ['Ȣ', 'ɔ']
                    {
                        if (ch <= 591u) // ['Ȣ', 'ɏ']
                        {
                            if (ch <= 572u) // ['Ȣ', 'ȼ']
                            {
                                if (ch <= 563u) // ['Ȣ', 'ȳ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ȣ', 'ȳ']
                                else if (ch >= 571u) // ['Ȼ', 'ȼ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ȼ', 'ȼ']
                            } // ['Ȣ', 'ȼ']
                            else if (ch >= 577u) // ['Ɂ', 'ɏ']
                            {
                                if (ch <= 578u) // ['Ɂ', 'ɂ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ɂ', 'ɂ']
                                else if (ch >= 582u) // ['Ɇ', 'ɏ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ɇ', 'ɏ']
                            } // ['Ɂ', 'ɏ']
                        } // ['Ȣ', 'ɏ']
                        else if (ch >= 592u) // ['ɐ', 'ɔ']
                        {
                            if (ch <= 593u) // ['ɐ', 'ɑ']
                            {
                                if (ch <= 592u) // ['ɐ', 'ɐ']
                                {
                                    diff = -10783;
                                    goto APPLY_DIFF;
                                } // ['ɐ', 'ɐ']
                                else if (ch >= 593u) // ['ɑ', 'ɑ']
                                {
                                    diff = -10780;
                                    goto APPLY_DIFF;
                                } // ['ɑ', 'ɑ']
                            } // ['ɐ', 'ɑ']
                            else if (ch >= 595u) // ['ɓ', 'ɔ']
                            {
                                if (ch <= 595u) // ['ɓ', 'ɓ']
                                {
                                    diff = 210;
                                    goto APPLY_DIFF;
                                } // ['ɓ', 'ɓ']
                                else if (ch >= 596u) // ['ɔ', 'ɔ']
                                {
                                    diff = 206;
                                    goto APPLY_DIFF;
                                } // ['ɔ', 'ɔ']
                            } // ['ɓ', 'ɔ']
                        } // ['ɐ', 'ɔ']
                    } // ['Ȣ', 'ɔ']
                    else if (ch >= 598u) // ['ɖ', 'ɯ']
                    {
                        if (ch <= 608u) // ['ɖ', 'ɠ']
                        {
                            if (ch <= 601u) // ['ɖ', 'ə']
                            {
                                if (ch <= 599u) // ['ɖ', 'ɗ']
                                {
                                    diff = 205;
                                    goto APPLY_DIFF;
                                } // ['ɖ', 'ɗ']
                                else if (ch >= 601u) // ['ə', 'ə']
                                {
                                    diff = 202;
                                    goto APPLY_DIFF;
                                } // ['ə', 'ə']
                            } // ['ɖ', 'ə']
                            else if (ch >= 603u) // ['ɛ', 'ɠ']
                            {
                                if (ch <= 603u) // ['ɛ', 'ɛ']
                                {
                                    diff = 203;
                                    goto APPLY_DIFF;
                                } // ['ɛ', 'ɛ']
                                else if (ch >= 608u) // ['ɠ', 'ɠ']
                                {
                                    diff = 205;
                                    goto APPLY_DIFF;
                                } // ['ɠ', 'ɠ']
                            } // ['ɛ', 'ɠ']
                        } // ['ɖ', 'ɠ']
                        else if (ch >= 611u) // ['ɣ', 'ɯ']
                        {
                            if (ch <= 616u) // ['ɣ', 'ɨ']
                            {
                                if (ch <= 611u) // ['ɣ', 'ɣ']
                                {
                                    diff = 207;
                                    goto APPLY_DIFF;
                                } // ['ɣ', 'ɣ']
                                else if (ch >= 616u) // ['ɨ', 'ɨ']
                                {
                                    diff = 209;
                                    goto APPLY_DIFF;
                                } // ['ɨ', 'ɨ']
                            } // ['ɣ', 'ɨ']
                            else if (ch >= 617u) // ['ɩ', 'ɯ']
                            {
                                if (ch <= 617u) // ['ɩ', 'ɩ']
                                {
                                    diff = 211;
                                    goto APPLY_DIFF;
                                } // ['ɩ', 'ɩ']
                                else if (ch >= 619u) // ['ɫ', 'ɯ']
                                {
                                    if (ch <= 619u) // ['ɫ', 'ɫ']
                                    {
                                        diff = -10743;
                                        goto APPLY_DIFF;
                                    } // ['ɫ', 'ɫ']
                                    else if (ch >= 623u) // ['ɯ', 'ɯ']
                                    {
                                        diff = 211;
                                        goto APPLY_DIFF;
                                    } // ['ɯ', 'ɯ']
                                } // ['ɫ', 'ɯ']
                            } // ['ɩ', 'ɯ']
                        } // ['ɣ', 'ɯ']
                    } // ['ɖ', 'ɯ']
                } // ['Ȣ', 'ɯ']
                else if (ch >= 625u) // ['ɱ', 'ρ']
                {
                    if (ch <= 649u) // ['ɱ', 'ʉ']
                    {
                        if (ch <= 637u) // ['ɱ', 'ɽ']
                        {
                            if (ch <= 626u) // ['ɱ', 'ɲ']
                            {
                                if (ch <= 625u) // ['ɱ', 'ɱ']
                                {
                                    diff = -10749;
                                    goto APPLY_DIFF;
                                } // ['ɱ', 'ɱ']
                                else if (ch >= 626u) // ['ɲ', 'ɲ']
                                {
                                    diff = 213;
                                    goto APPLY_DIFF;
                                } // ['ɲ', 'ɲ']
                            } // ['ɱ', 'ɲ']
                            else if (ch >= 629u) // ['ɵ', 'ɽ']
                            {
                                if (ch <= 629u) // ['ɵ', 'ɵ']
                                {
                                    diff = 214;
                                    goto APPLY_DIFF;
                                } // ['ɵ', 'ɵ']
                                else if (ch >= 637u) // ['ɽ', 'ɽ']
                                {
                                    diff = -10727;
                                    goto APPLY_DIFF;
                                } // ['ɽ', 'ɽ']
                            } // ['ɵ', 'ɽ']
                        } // ['ɱ', 'ɽ']
                        else if (ch >= 640u) // ['ʀ', 'ʉ']
                        {
                            if (ch <= 643u) // ['ʀ', 'ʃ']
                            {
                                if (ch <= 640u) // ['ʀ', 'ʀ']
                                {
                                    diff = 218;
                                    goto APPLY_DIFF;
                                } // ['ʀ', 'ʀ']
                                else if (ch >= 643u) // ['ʃ', 'ʃ']
                                {
                                    diff = 218;
                                    goto APPLY_DIFF;
                                } // ['ʃ', 'ʃ']
                            } // ['ʀ', 'ʃ']
                            else if (ch >= 648u) // ['ʈ', 'ʉ']
                            {
                                if (ch <= 648u) // ['ʈ', 'ʈ']
                                {
                                    diff = 218;
                                    goto APPLY_DIFF;
                                } // ['ʈ', 'ʈ']
                                else if (ch >= 649u) // ['ʉ', 'ʉ']
                                {
                                    diff = 69;
                                    goto APPLY_DIFF;
                                } // ['ʉ', 'ʉ']
                            } // ['ʈ', 'ʉ']
                        } // ['ʀ', 'ʉ']
                    } // ['ɱ', 'ʉ']
                    else if (ch >= 650u) // ['ʊ', 'ρ']
                    {
                        if (ch <= 883u) // ['ʊ', 'ͳ']
                        {
                            if (ch <= 652u) // ['ʊ', 'ʌ']
                            {
                                if (ch <= 651u) // ['ʊ', 'ʋ']
                                {
                                    diff = 217;
                                    goto APPLY_DIFF;
                                } // ['ʊ', 'ʋ']
                                else if (ch >= 652u) // ['ʌ', 'ʌ']
                                {
                                    diff = 71;
                                    goto APPLY_DIFF;
                                } // ['ʌ', 'ʌ']
                            } // ['ʊ', 'ʌ']
                            else if (ch >= 658u) // ['ʒ', 'ͳ']
                            {
                                if (ch <= 658u) // ['ʒ', 'ʒ']
                                {
                                    diff = 219;
                                    goto APPLY_DIFF;
                                } // ['ʒ', 'ʒ']
                                else if (ch >= 880u) // ['Ͱ', 'ͳ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ͱ', 'ͳ']
                            } // ['ʒ', 'ͳ']
                        } // ['ʊ', 'ͳ']
                        else if (ch >= 886u) // ['Ͷ', 'ρ']
                        {
                            if (ch <= 893u) // ['Ͷ', 'ͽ']
                            {
                                if (ch <= 887u) // ['Ͷ', 'ͷ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ͷ', 'ͷ']
                                else if (ch >= 891u) // ['ͻ', 'ͽ']
                                {
                                    diff = -130;
                                    goto APPLY_DIFF;
                                } // ['ͻ', 'ͽ']
                            } // ['Ͷ', 'ͽ']
                            else if (ch >= 940u) // ['ά', 'ρ']
                            {
                                if (ch <= 940u) // ['ά', 'ά']
                                {
                                    diff = 38;
                                    goto APPLY_DIFF;
                                } // ['ά', 'ά']
                                else if (ch >= 941u) // ['έ', 'ρ']
                                {
                                    if (ch <= 943u) // ['έ', 'ί']
                                    {
                                        diff = 37;
                                        goto APPLY_DIFF;
                                    } // ['έ', 'ί']
                                    else if (ch >= 945u) // ['α', 'ρ']
                                    {
                                        diff = 32;
                                        goto APPLY_DIFF;
                                    } // ['α', 'ρ']
                                } // ['έ', 'ρ']
                            } // ['ά', 'ρ']
                        } // ['Ͷ', 'ρ']
                    } // ['ʊ', 'ρ']
                } // ['ɱ', 'ρ']
            } // ['Ȣ', 'ρ']
        } // ['à', 'ρ']
        else if (ch >= 963u) // ['σ', 'ｚ']
        {
            if (ch <= 8057u) // ['σ', 'ό']
            {
                if (ch <= 7545u) // ['σ', 'ᵹ']
                {
                    if (ch <= 1019u) // ['σ', 'ϻ']
                    {
                        if (ch <= 983u) // ['σ', 'ϗ']
                        {
                            if (ch <= 972u) // ['σ', 'ό']
                            {
                                if (ch <= 971u) // ['σ', 'ϋ']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['σ', 'ϋ']
                                else if (ch >= 972u) // ['ό', 'ό']
                                {
                                    diff = 64;
                                    goto APPLY_DIFF;
                                } // ['ό', 'ό']
                            } // ['σ', 'ό']
                            else if (ch >= 973u) // ['ύ', 'ϗ']
                            {
                                if (ch <= 974u) // ['ύ', 'ώ']
                                {
                                    diff = 63;
                                    goto APPLY_DIFF;
                                } // ['ύ', 'ώ']
                                else if (ch >= 983u) // ['ϗ', 'ϗ']
                                {
                                    diff = 8;
                                    goto APPLY_DIFF;
                                } // ['ϗ', 'ϗ']
                            } // ['ύ', 'ϗ']
                        } // ['σ', 'ϗ']
                        else if (ch >= 984u) // ['Ϙ', 'ϻ']
                        {
                            if (ch <= 1010u) // ['Ϙ', 'ϲ']
                            {
                                if (ch <= 1007u) // ['Ϙ', 'ϯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ϙ', 'ϯ']
                                else if (ch >= 1010u) // ['ϲ', 'ϲ']
                                {
                                    diff = -7;
                                    goto APPLY_DIFF;
                                } // ['ϲ', 'ϲ']
                            } // ['Ϙ', 'ϲ']
                            else if (ch >= 1015u) // ['Ϸ', 'ϻ']
                            {
                                if (ch <= 1016u) // ['Ϸ', 'ϸ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ϸ', 'ϸ']
                                else if (ch >= 1018u) // ['Ϻ', 'ϻ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ϻ', 'ϻ']
                            } // ['Ϸ', 'ϻ']
                        } // ['Ϙ', 'ϻ']
                    } // ['σ', 'ϻ']
                    else if (ch >= 1072u) // ['а', 'ᵹ']
                    {
                        if (ch <= 1215u) // ['а', 'ҿ']
                        {
                            if (ch <= 1119u) // ['а', 'џ']
                            {
                                if (ch <= 1103u) // ['а', 'я']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['а', 'я']
                                else if (ch >= 1104u) // ['ѐ', 'џ']
                                {
                                    diff = 80;
                                    goto APPLY_DIFF;
                                } // ['ѐ', 'џ']
                            } // ['а', 'џ']
                            else if (ch >= 1120u) // ['Ѡ', 'ҿ']
                            {
                                if (ch <= 1153u) // ['Ѡ', 'ҁ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ѡ', 'ҁ']
                                else if (ch >= 1162u) // ['Ҋ', 'ҿ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ҋ', 'ҿ']
                            } // ['Ѡ', 'ҿ']
                        } // ['а', 'ҿ']
                        else if (ch >= 1217u) // ['Ӂ', 'ᵹ']
                        {
                            if (ch <= 1231u) // ['Ӂ', 'ӏ']
                            {
                                if (ch <= 1230u) // ['Ӂ', 'ӎ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ӂ', 'ӎ']
                                else if (ch >= 1231u) // ['ӏ', 'ӏ']
                                {
                                    diff = 15;
                                    goto APPLY_DIFF;
                                } // ['ӏ', 'ӏ']
                            } // ['Ӂ', 'ӏ']
                            else if (ch >= 1232u) // ['Ӑ', 'ᵹ']
                            {
                                if (ch <= 1315u) // ['Ӑ', 'ԣ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ӑ', 'ԣ']
                                else if (ch >= 1377u) // ['ա', 'ᵹ']
                                {
                                    if (ch <= 1414u) // ['ա', 'ֆ']
                                    {
                                        diff = 48;
                                        goto APPLY_DIFF;
                                    } // ['ա', 'ֆ']
                                    else if (ch >= 7545u) // ['ᵹ', 'ᵹ']
                                    {
                                        diff = -35332;
                                        goto APPLY_DIFF;
                                    } // ['ᵹ', 'ᵹ']
                                } // ['ա', 'ᵹ']
                            } // ['Ӑ', 'ᵹ']
                        } // ['Ӂ', 'ᵹ']
                    } // ['а', 'ᵹ']
                } // ['σ', 'ᵹ']
                else if (ch >= 7549u) // ['ᵽ', 'ό']
                {
                    if (ch <= 8005u) // ['ᵽ', 'ὅ']
                    {
                        if (ch <= 7943u) // ['ᵽ', 'ἇ']
                        {
                            if (ch <= 7829u) // ['ᵽ', 'ẕ']
                            {
                                if (ch <= 7549u) // ['ᵽ', 'ᵽ']
                                {
                                    diff = -3814;
                                    goto APPLY_DIFF;
                                } // ['ᵽ', 'ᵽ']
                                else if (ch >= 7680u) // ['Ḁ', 'ẕ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ḁ', 'ẕ']
                            } // ['ᵽ', 'ẕ']
                            else if (ch >= 7840u) // ['Ạ', 'ἇ']
                            {
                                if (ch <= 7935u) // ['Ạ', 'ỿ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ạ', 'ỿ']
                                else if (ch >= 7936u) // ['ἀ', 'ἇ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ἀ', 'ἇ']
                            } // ['Ạ', 'ἇ']
                        } // ['ᵽ', 'ἇ']
                        else if (ch >= 7952u) // ['ἐ', 'ὅ']
                        {
                            if (ch <= 7975u) // ['ἐ', 'ἧ']
                            {
                                if (ch <= 7957u) // ['ἐ', 'ἕ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ἐ', 'ἕ']
                                else if (ch >= 7968u) // ['ἠ', 'ἧ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ἠ', 'ἧ']
                            } // ['ἐ', 'ἧ']
                            else if (ch >= 7984u) // ['ἰ', 'ὅ']
                            {
                                if (ch <= 7991u) // ['ἰ', 'ἷ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ἰ', 'ἷ']
                                else if (ch >= 8000u) // ['ὀ', 'ὅ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ὀ', 'ὅ']
                            } // ['ἰ', 'ὅ']
                        } // ['ἐ', 'ὅ']
                    } // ['ᵽ', 'ὅ']
                    else if (ch >= 8017u) // ['ὑ', 'ό']
                    {
                        if (ch <= 8023u) // ['ὑ', 'ὗ']
                        {
                            if (ch <= 8019u) // ['ὑ', 'ὓ']
                            {
                                if (ch <= 8017u) // ['ὑ', 'ὑ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ὑ', 'ὑ']
                                else if (ch >= 8019u) // ['ὓ', 'ὓ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ὓ', 'ὓ']
                            } // ['ὑ', 'ὓ']
                            else if (ch >= 8021u) // ['ὕ', 'ὗ']
                            {
                                if (ch <= 8021u) // ['ὕ', 'ὕ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ὕ', 'ὕ']
                                else if (ch >= 8023u) // ['ὗ', 'ὗ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ὗ', 'ὗ']
                            } // ['ὕ', 'ὗ']
                        } // ['ὑ', 'ὗ']
                        else if (ch >= 8032u) // ['ὠ', 'ό']
                        {
                            if (ch <= 8049u) // ['ὠ', 'ά']
                            {
                                if (ch <= 8039u) // ['ὠ', 'ὧ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ὠ', 'ὧ']
                                else if (ch >= 8048u) // ['ὰ', 'ά']
                                {
                                    diff = -74;
                                    goto APPLY_DIFF;
                                } // ['ὰ', 'ά']
                            } // ['ὠ', 'ά']
                            else if (ch >= 8050u) // ['ὲ', 'ό']
                            {
                                if (ch <= 8053u) // ['ὲ', 'ή']
                                {
                                    diff = -86;
                                    goto APPLY_DIFF;
                                } // ['ὲ', 'ή']
                                else if (ch >= 8054u) // ['ὶ', 'ό']
                                {
                                    if (ch <= 8055u) // ['ὶ', 'ί']
                                    {
                                        diff = -100;
                                        goto APPLY_DIFF;
                                    } // ['ὶ', 'ί']
                                    else if (ch >= 8056u) // ['ὸ', 'ό']
                                    {
                                        diff = -128;
                                        goto APPLY_DIFF;
                                    } // ['ὸ', 'ό']
                                } // ['ὶ', 'ό']
                            } // ['ὲ', 'ό']
                        } // ['ὠ', 'ό']
                    } // ['ὑ', 'ό']
                } // ['ᵽ', 'ό']
            } // ['σ', 'ό']
            else if (ch >= 8058u) // ['ὺ', 'ｚ']
            {
                if (ch <= 11358u) // ['ὺ', 'ⱞ']
                {
                    if (ch <= 8131u) // ['ὺ', 'ῃ']
                    {
                        if (ch <= 8087u) // ['ὺ', 'ᾗ']
                        {
                            if (ch <= 8061u) // ['ὺ', 'ώ']
                            {
                                if (ch <= 8059u) // ['ὺ', 'ύ']
                                {
                                    diff = -112;
                                    goto APPLY_DIFF;
                                } // ['ὺ', 'ύ']
                                else if (ch >= 8060u) // ['ὼ', 'ώ']
                                {
                                    diff = -126;
                                    goto APPLY_DIFF;
                                } // ['ὼ', 'ώ']
                            } // ['ὺ', 'ώ']
                            else if (ch >= 8064u) // ['ᾀ', 'ᾗ']
                            {
                                if (ch <= 8071u) // ['ᾀ', 'ᾇ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾀ', 'ᾇ']
                                else if (ch >= 8080u) // ['ᾐ', 'ᾗ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾐ', 'ᾗ']
                            } // ['ᾀ', 'ᾗ']
                        } // ['ὺ', 'ᾗ']
                        else if (ch >= 8096u) // ['ᾠ', 'ῃ']
                        {
                            if (ch <= 8113u) // ['ᾠ', 'ᾱ']
                            {
                                if (ch <= 8103u) // ['ᾠ', 'ᾧ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾠ', 'ᾧ']
                                else if (ch >= 8112u) // ['ᾰ', 'ᾱ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾰ', 'ᾱ']
                            } // ['ᾠ', 'ᾱ']
                            else if (ch >= 8115u) // ['ᾳ', 'ῃ']
                            {
                                if (ch <= 8115u) // ['ᾳ', 'ᾳ']
                                {
                                    diff = -9;
                                    goto APPLY_DIFF;
                                } // ['ᾳ', 'ᾳ']
                                else if (ch >= 8131u) // ['ῃ', 'ῃ']
                                {
                                    diff = -9;
                                    goto APPLY_DIFF;
                                } // ['ῃ', 'ῃ']
                            } // ['ᾳ', 'ῃ']
                        } // ['ᾠ', 'ῃ']
                    } // ['ὺ', 'ῃ']
                    else if (ch >= 8144u) // ['ῐ', 'ⱞ']
                    {
                        if (ch <= 8179u) // ['ῐ', 'ῳ']
                        {
                            if (ch <= 8161u) // ['ῐ', 'ῡ']
                            {
                                if (ch <= 8145u) // ['ῐ', 'ῑ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ῐ', 'ῑ']
                                else if (ch >= 8160u) // ['ῠ', 'ῡ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ῠ', 'ῡ']
                            } // ['ῐ', 'ῡ']
                            else if (ch >= 8165u) // ['ῥ', 'ῳ']
                            {
                                if (ch <= 8165u) // ['ῥ', 'ῥ']
                                {
                                    diff = -7;
                                    goto APPLY_DIFF;
                                } // ['ῥ', 'ῥ']
                                else if (ch >= 8179u) // ['ῳ', 'ῳ']
                                {
                                    diff = -9;
                                    goto APPLY_DIFF;
                                } // ['ῳ', 'ῳ']
                            } // ['ῥ', 'ῳ']
                        } // ['ῐ', 'ῳ']
                        else if (ch >= 8526u) // ['ⅎ', 'ⱞ']
                        {
                            if (ch <= 8575u) // ['ⅎ', 'ⅿ']
                            {
                                if (ch <= 8526u) // ['ⅎ', 'ⅎ']
                                {
                                    diff = 28;
                                    goto APPLY_DIFF;
                                } // ['ⅎ', 'ⅎ']
                                else if (ch >= 8560u) // ['ⅰ', 'ⅿ']
                                {
                                    diff = 16;
                                    goto APPLY_DIFF;
                                } // ['ⅰ', 'ⅿ']
                            } // ['ⅎ', 'ⅿ']
                            else if (ch >= 8579u) // ['Ↄ', 'ⱞ']
                            {
                                if (ch <= 8580u) // ['Ↄ', 'ↄ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ↄ', 'ↄ']
                                else if (ch >= 9424u) // ['ⓐ', 'ⱞ']
                                {
                                    if (ch <= 9449u) // ['ⓐ', 'ⓩ']
                                    {
                                        diff = 26;
                                        goto APPLY_DIFF;
                                    } // ['ⓐ', 'ⓩ']
                                    else if (ch >= 11312u) // ['ⰰ', 'ⱞ']
                                    {
                                        diff = 48;
                                        goto APPLY_DIFF;
                                    } // ['ⰰ', 'ⱞ']
                                } // ['ⓐ', 'ⱞ']
                            } // ['Ↄ', 'ⱞ']
                        } // ['ⅎ', 'ⱞ']
                    } // ['ῐ', 'ⱞ']
                } // ['ὺ', 'ⱞ']
                else if (ch >= 11360u) // ['Ⱡ', 'ｚ']
                {
                    if (ch <= 11557u) // ['Ⱡ', 'ⴥ']
                    {
                        if (ch <= 11372u) // ['Ⱡ', 'ⱬ']
                        {
                            if (ch <= 11365u) // ['Ⱡ', 'ⱥ']
                            {
                                if (ch <= 11361u) // ['Ⱡ', 'ⱡ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ⱡ', 'ⱡ']
                                else if (ch >= 11365u) // ['ⱥ', 'ⱥ']
                                {
                                    diff = 10795;
                                    goto APPLY_DIFF;
                                } // ['ⱥ', 'ⱥ']
                            } // ['Ⱡ', 'ⱥ']
                            else if (ch >= 11366u) // ['ⱦ', 'ⱬ']
                            {
                                if (ch <= 11366u) // ['ⱦ', 'ⱦ']
                                {
                                    diff = 10792;
                                    goto APPLY_DIFF;
                                } // ['ⱦ', 'ⱦ']
                                else if (ch >= 11367u) // ['Ⱨ', 'ⱬ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ⱨ', 'ⱬ']
                            } // ['ⱦ', 'ⱬ']
                        } // ['Ⱡ', 'ⱬ']
                        else if (ch >= 11378u) // ['Ⱳ', 'ⴥ']
                        {
                            if (ch <= 11382u) // ['Ⱳ', 'ⱶ']
                            {
                                if (ch <= 11379u) // ['Ⱳ', 'ⱳ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ⱳ', 'ⱳ']
                                else if (ch >= 11381u) // ['Ⱶ', 'ⱶ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ⱶ', 'ⱶ']
                            } // ['Ⱳ', 'ⱶ']
                            else if (ch >= 11392u) // ['Ⲁ', 'ⴥ']
                            {
                                if (ch <= 11491u) // ['Ⲁ', 'ⳣ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ⲁ', 'ⳣ']
                                else if (ch >= 11520u) // ['ⴀ', 'ⴥ']
                                {
                                    diff = 7264;
                                    goto APPLY_DIFF;
                                } // ['ⴀ', 'ⴥ']
                            } // ['Ⲁ', 'ⴥ']
                        } // ['Ⱳ', 'ⴥ']
                    } // ['Ⱡ', 'ⴥ']
                    else if (ch >= 42560u) // ['Ꙁ', 'ｚ']
                    {
                        if (ch <= 42799u) // ['Ꙁ', 'ꜯ']
                        {
                            if (ch <= 42605u) // ['Ꙁ', 'ꙭ']
                            {
                                if (ch <= 42591u) // ['Ꙁ', 'ꙟ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꙁ', 'ꙟ']
                                else if (ch >= 42594u) // ['Ꙣ', 'ꙭ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꙣ', 'ꙭ']
                            } // ['Ꙁ', 'ꙭ']
                            else if (ch >= 42624u) // ['Ꚁ', 'ꜯ']
                            {
                                if (ch <= 42647u) // ['Ꚁ', 'ꚗ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꚁ', 'ꚗ']
                                else if (ch >= 42786u) // ['Ꜣ', 'ꜯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꜣ', 'ꜯ']
                            } // ['Ꚁ', 'ꜯ']
                        } // ['Ꙁ', 'ꜯ']
                        else if (ch >= 42802u) // ['Ꜳ', 'ｚ']
                        {
                            if (ch <= 42876u) // ['Ꜳ', 'ꝼ']
                            {
                                if (ch <= 42863u) // ['Ꜳ', 'ꝯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꜳ', 'ꝯ']
                                else if (ch >= 42873u) // ['Ꝺ', 'ꝼ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ꝺ', 'ꝼ']
                            } // ['Ꜳ', 'ꝼ']
                            else if (ch >= 42878u) // ['Ꝿ', 'ｚ']
                            {
                                if (ch <= 42887u) // ['Ꝿ', 'ꞇ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꝿ', 'ꞇ']
                                else if (ch >= 42891u) // ['Ꞌ', 'ｚ']
                                {
                                    if (ch <= 42892u) // ['Ꞌ', 'ꞌ']
                                    {
                                        goto UPPERCASE_IS_ODD;
                                    } // ['Ꞌ', 'ꞌ']
                                    else if (ch >= 65345u) // ['ａ', 'ｚ']
                                    {
                                        diff = 32;
                                        goto APPLY_DIFF;
                                    } // ['ａ', 'ｚ']
                                } // ['Ꞌ', 'ｚ']
                            } // ['Ꝿ', 'ｚ']
                        } // ['Ꜳ', 'ｚ']
                    } // ['Ꙁ', 'ｚ']
                } // ['Ⱡ', 'ｚ']
            } // ['ὺ', 'ｚ']
        } // ['σ', 'ｚ']
    }


    // no change
    return ch;

    APPLY_DIFF:
    return (char32_t)(ch - diff);

    UPPERCASE_IS_EVEN:
    return (char32_t)(ch & ~1u);

    UPPERCASE_IS_ODD:
    return (char32_t)((ch - 1) | 1u);
}

char32_t Utf8::ToLower(char32_t ch)
{
    int32_t diff = 0;
    if (ch >= 65u && ch <= 90u) // ['A', 'Z']
    {
        diff = 32;
        goto APPLY_DIFF;
    }

    if (ch >= 192u && ch <= 65338u) // ['À', 'Ｚ']
    {
        if (ch <= 975u) // ['À', 'Ϗ']
        {
            if (ch <= 434u) // ['À', 'Ʋ']
            {
                if (ch <= 400u) // ['À', 'Ɛ']
                {
                    if (ch <= 382u) // ['À', 'ž']
                    {
                        if (ch <= 311u) // ['À', 'ķ']
                        {
                            if (ch <= 222u) // ['À', 'Þ']
                            {
                                if (ch <= 214u) // ['À', 'Ö']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['À', 'Ö']
                                else if (ch >= 216u) // ['Ø', 'Þ']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['Ø', 'Þ']
                            } // ['À', 'Þ']
                            else if (ch >= 256u) // ['Ā', 'ķ']
                            {
                                if (ch <= 303u) // ['Ā', 'į']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ā', 'į']
                                else if (ch >= 306u) // ['Ĳ', 'ķ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ĳ', 'ķ']
                            } // ['Ā', 'ķ']
                        } // ['À', 'ķ']
                        else if (ch >= 313u) // ['Ĺ', 'ž']
                        {
                            if (ch <= 375u) // ['Ĺ', 'ŷ']
                            {
                                if (ch <= 328u) // ['Ĺ', 'ň']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ĺ', 'ň']
                                else if (ch >= 330u) // ['Ŋ', 'ŷ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ŋ', 'ŷ']
                            } // ['Ĺ', 'ŷ']
                            else if (ch >= 376u) // ['Ÿ', 'ž']
                            {
                                if (ch <= 376u) // ['Ÿ', 'Ÿ']
                                {
                                    diff = -121;

                                    goto APPLY_DIFF;
                                } // ['Ÿ', 'Ÿ']
                                else if (ch >= 377u) // ['Ź', 'ž']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ź', 'ž']
                            } // ['Ÿ', 'ž']
                        } // ['Ĺ', 'ž']
                    } // ['À', 'ž']
                    else if (ch >= 385u) // ['Ɓ', 'Ɛ']
                    {
                        if (ch <= 392u) // ['Ɓ', 'ƈ']
                        {
                            if (ch <= 389u) // ['Ɓ', 'ƅ']
                            {
                                if (ch <= 385u) // ['Ɓ', 'Ɓ']
                                {
                                    diff = 210;
                                    goto APPLY_DIFF;
                                } // ['Ɓ', 'Ɓ']
                                else if (ch >= 386u) // ['Ƃ', 'ƅ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƃ', 'ƅ']
                            } // ['Ɓ', 'ƅ']
                            else if (ch >= 390u) // ['Ɔ', 'ƈ']
                            {
                                if (ch <= 390u) // ['Ɔ', 'Ɔ']
                                {
                                    diff = 206;
                                    goto APPLY_DIFF;
                                } // ['Ɔ', 'Ɔ']
                                else if (ch >= 391u) // ['Ƈ', 'ƈ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƈ', 'ƈ']
                            } // ['Ɔ', 'ƈ']
                        } // ['Ɓ', 'ƈ']
                        else if (ch >= 393u) // ['Ɖ', 'Ɛ']
                        {
                            if (ch <= 396u) // ['Ɖ', 'ƌ']
                            {
                                if (ch <= 394u) // ['Ɖ', 'Ɗ']
                                {
                                    diff = 205;
                                    goto APPLY_DIFF;
                                } // ['Ɖ', 'Ɗ']
                                else if (ch >= 395u) // ['Ƌ', 'ƌ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƌ', 'ƌ']
                            } // ['Ɖ', 'ƌ']
                            else if (ch >= 398u) // ['Ǝ', 'Ɛ']
                            {
                                if (ch <= 398u) // ['Ǝ', 'Ǝ']
                                {
                                    diff = 79;
                                    goto APPLY_DIFF;
                                } // ['Ǝ', 'Ǝ']
                                else if (ch >= 399u) // ['Ə', 'Ɛ']
                                {
                                    if (ch <= 399u) // ['Ə', 'Ə']
                                    {
                                        diff = 202;
                                        goto APPLY_DIFF;
                                    } // ['Ə', 'Ə']
                                    else if (ch >= 400u) // ['Ɛ', 'Ɛ']
                                    {
                                        diff = 203;
                                        goto APPLY_DIFF;
                                    } // ['Ɛ', 'Ɛ']
                                } // ['Ə', 'Ɛ']
                            } // ['Ǝ', 'Ɛ']
                        } // ['Ɖ', 'Ɛ']
                    } // ['Ɓ', 'Ɛ']
                } // ['À', 'Ɛ']
                else if (ch >= 401u) // ['Ƒ', 'Ʋ']
                {
                    if (ch <= 413u) // ['Ƒ', 'Ɲ']
                    {
                        if (ch <= 406u) // ['Ƒ', 'Ɩ']
                        {
                            if (ch <= 403u) // ['Ƒ', 'Ɠ']
                            {
                                if (ch <= 402u) // ['Ƒ', 'ƒ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƒ', 'ƒ']
                                else if (ch >= 403u) // ['Ɠ', 'Ɠ']
                                {
                                    diff = 205;
                                    goto APPLY_DIFF;
                                } // ['Ɠ', 'Ɠ']
                            } // ['Ƒ', 'Ɠ']
                            else if (ch >= 404u) // ['Ɣ', 'Ɩ']
                            {
                                if (ch <= 404u) // ['Ɣ', 'Ɣ']
                                {
                                    diff = 207;
                                    goto APPLY_DIFF;
                                } // ['Ɣ', 'Ɣ']
                                else if (ch >= 406u) // ['Ɩ', 'Ɩ']
                                {
                                    diff = 211;
                                    goto APPLY_DIFF;
                                } // ['Ɩ', 'Ɩ']
                            } // ['Ɣ', 'Ɩ']
                        } // ['Ƒ', 'Ɩ']
                        else if (ch >= 407u) // ['Ɨ', 'Ɲ']
                        {
                            if (ch <= 409u) // ['Ɨ', 'ƙ']
                            {
                                if (ch <= 407u) // ['Ɨ', 'Ɨ']
                                {
                                    diff = 209;
                                    goto APPLY_DIFF;
                                } // ['Ɨ', 'Ɨ']
                                else if (ch >= 408u) // ['Ƙ', 'ƙ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƙ', 'ƙ']
                            } // ['Ɨ', 'ƙ']
                            else if (ch >= 412u) // ['Ɯ', 'Ɲ']
                            {
                                if (ch <= 412u) // ['Ɯ', 'Ɯ']
                                {
                                    diff = 211;
                                    goto APPLY_DIFF;
                                } // ['Ɯ', 'Ɯ']
                                else if (ch >= 413u) // ['Ɲ', 'Ɲ']
                                {
                                    diff = 213;
                                    goto APPLY_DIFF;
                                } // ['Ɲ', 'Ɲ']
                            } // ['Ɯ', 'Ɲ']
                        } // ['Ɨ', 'Ɲ']
                    } // ['Ƒ', 'Ɲ']
                    else if (ch >= 415u) // ['Ɵ', 'Ʋ']
                    {
                        if (ch <= 424u) // ['Ɵ', 'ƨ']
                        {
                            if (ch <= 421u) // ['Ɵ', 'ƥ']
                            {
                                if (ch <= 415u) // ['Ɵ', 'Ɵ']
                                {
                                    diff = 214;
                                    goto APPLY_DIFF;
                                } // ['Ɵ', 'Ɵ']
                                else if (ch >= 416u) // ['Ơ', 'ƥ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ơ', 'ƥ']
                            } // ['Ɵ', 'ƥ']
                            else if (ch >= 422u) // ['Ʀ', 'ƨ']
                            {
                                if (ch <= 422u) // ['Ʀ', 'Ʀ']
                                {
                                    diff = 218;
                                    goto APPLY_DIFF;
                                } // ['Ʀ', 'Ʀ']
                                else if (ch >= 423u) // ['Ƨ', 'ƨ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƨ', 'ƨ']
                            } // ['Ʀ', 'ƨ']
                        } // ['Ɵ', 'ƨ']
                        else if (ch >= 425u) // ['Ʃ', 'Ʋ']
                        {
                            if (ch <= 429u) // ['Ʃ', 'ƭ']
                            {
                                if (ch <= 425u) // ['Ʃ', 'Ʃ']
                                {
                                    diff = 218;
                                    goto APPLY_DIFF;
                                } // ['Ʃ', 'Ʃ']
                                else if (ch >= 428u) // ['Ƭ', 'ƭ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƭ', 'ƭ']
                            } // ['Ʃ', 'ƭ']
                            else if (ch >= 430u) // ['Ʈ', 'Ʋ']
                            {
                                if (ch <= 430u) // ['Ʈ', 'Ʈ']
                                {
                                    diff = 218;
                                    goto APPLY_DIFF;
                                } // ['Ʈ', 'Ʈ']
                                else if (ch >= 431u) // ['Ư', 'Ʋ']
                                {
                                    if (ch <= 432u) // ['Ư', 'ư']
                                    {
                                        goto UPPERCASE_IS_ODD;
                                    } // ['Ư', 'ư']
                                    else if (ch >= 433u) // ['Ʊ', 'Ʋ']
                                    {
                                        diff = 217;
                                        goto APPLY_DIFF;
                                    } // ['Ʊ', 'Ʋ']
                                } // ['Ư', 'Ʋ']
                            } // ['Ʈ', 'Ʋ']
                        } // ['Ʃ', 'Ʋ']
                    } // ['Ɵ', 'Ʋ']
                } // ['Ƒ', 'Ʋ']
            } // ['À', 'Ʋ']
            else if (ch >= 435u) // ['Ƴ', 'Ϗ']
            {
                if (ch <= 570u) // ['Ƴ', 'Ⱥ']
                {
                    if (ch <= 476u) // ['Ƴ', 'ǜ']
                    {
                        if (ch <= 445u) // ['Ƴ', 'ƽ']
                        {
                            if (ch <= 439u) // ['Ƴ', 'Ʒ']
                            {
                                if (ch <= 438u) // ['Ƴ', 'ƶ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ƴ', 'ƶ']
                                else if (ch >= 439u) // ['Ʒ', 'Ʒ']
                                {
                                    diff = 219;
                                    goto APPLY_DIFF;
                                } // ['Ʒ', 'Ʒ']
                            } // ['Ƴ', 'Ʒ']
                            else if (ch >= 440u) // ['Ƹ', 'ƽ']
                            {
                                if (ch <= 441u) // ['Ƹ', 'ƹ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƹ', 'ƹ']
                                else if (ch >= 444u) // ['Ƽ', 'ƽ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ƽ', 'ƽ']
                            } // ['Ƹ', 'ƽ']
                        } // ['Ƴ', 'ƽ']
                        else if (ch >= 452u) // ['Ǆ', 'ǜ']
                        {
                            if (ch <= 455u) // ['Ǆ', 'Ǉ']
                            {
                                if (ch <= 452u) // ['Ǆ', 'Ǆ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['Ǆ', 'Ǆ']
                                else if (ch >= 455u) // ['Ǉ', 'Ǉ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['Ǉ', 'Ǉ']
                            } // ['Ǆ', 'Ǉ']
                            else if (ch >= 458u) // ['Ǌ', 'ǜ']
                            {
                                if (ch <= 458u) // ['Ǌ', 'Ǌ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['Ǌ', 'Ǌ']
                                else if (ch >= 461u) // ['Ǎ', 'ǜ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ǎ', 'ǜ']
                            } // ['Ǌ', 'ǜ']
                        } // ['Ǆ', 'ǜ']
                    } // ['Ƴ', 'ǜ']
                    else if (ch >= 478u) // ['Ǟ', 'Ⱥ']
                    {
                        if (ch <= 502u) // ['Ǟ', 'Ƕ']
                        {
                            if (ch <= 497u) // ['Ǟ', 'Ǳ']
                            {
                                if (ch <= 495u) // ['Ǟ', 'ǯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ǟ', 'ǯ']
                                else if (ch >= 497u) // ['Ǳ', 'Ǳ']
                                {
                                    diff = 2;
                                    goto APPLY_DIFF;
                                } // ['Ǳ', 'Ǳ']
                            } // ['Ǟ', 'Ǳ']
                            else if (ch >= 500u) // ['Ǵ', 'Ƕ']
                            {
                                if (ch <= 501u) // ['Ǵ', 'ǵ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ǵ', 'ǵ']
                                else if (ch >= 502u) // ['Ƕ', 'Ƕ']
                                {
                                    diff = -97;
                                    goto APPLY_DIFF;
                                } // ['Ƕ', 'Ƕ']
                            } // ['Ǵ', 'Ƕ']
                        } // ['Ǟ', 'Ƕ']
                        else if (ch >= 503u) // ['Ƿ', 'Ⱥ']
                        {
                            if (ch <= 543u) // ['Ƿ', 'ȟ']
                            {
                                if (ch <= 503u) // ['Ƿ', 'Ƿ']
                                {
                                    diff = -56;
                                    goto APPLY_DIFF;
                                } // ['Ƿ', 'Ƿ']
                                else if (ch >= 504u) // ['Ǹ', 'ȟ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ǹ', 'ȟ']
                            } // ['Ƿ', 'ȟ']
                            else if (ch >= 544u) // ['Ƞ', 'Ⱥ']
                            {
                                if (ch <= 544u) // ['Ƞ', 'Ƞ']
                                {
                                    diff = -130;
                                    goto APPLY_DIFF;
                                } // ['Ƞ', 'Ƞ']
                                else if (ch >= 546u) // ['Ȣ', 'Ⱥ']
                                {
                                    if (ch <= 563u) // ['Ȣ', 'ȳ']
                                    {
                                        goto UPPERCASE_IS_EVEN;
                                    } // ['Ȣ', 'ȳ']
                                    else if (ch >= 570u) // ['Ⱥ', 'Ⱥ']
                                    {
                                        diff = 10795;
                                        goto APPLY_DIFF;
                                    } // ['Ⱥ', 'Ⱥ']
                                } // ['Ȣ', 'Ⱥ']
                            } // ['Ƞ', 'Ⱥ']
                        } // ['Ƿ', 'Ⱥ']
                    } // ['Ǟ', 'Ⱥ']
                } // ['Ƴ', 'Ⱥ']
                else if (ch >= 571u) // ['Ȼ', 'Ϗ']
                {
                    if (ch <= 591u) // ['Ȼ', 'ɏ']
                    {
                        if (ch <= 578u) // ['Ȼ', 'ɂ']
                        {
                            if (ch <= 573u) // ['Ȼ', 'Ƚ']
                            {
                                if (ch <= 572u) // ['Ȼ', 'ȼ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ȼ', 'ȼ']
                                else if (ch >= 573u) // ['Ƚ', 'Ƚ']
                                {
                                    diff = -163;
                                    goto APPLY_DIFF;
                                } // ['Ƚ', 'Ƚ']
                            } // ['Ȼ', 'Ƚ']
                            else if (ch >= 574u) // ['Ⱦ', 'ɂ']
                            {
                                if (ch <= 574u) // ['Ⱦ', 'Ⱦ']
                                {
                                    diff = 10792;
                                    goto APPLY_DIFF;
                                } // ['Ⱦ', 'Ⱦ']
                                else if (ch >= 577u) // ['Ɂ', 'ɂ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ɂ', 'ɂ']
                            } // ['Ⱦ', 'ɂ']
                        } // ['Ȼ', 'ɂ']
                        else if (ch >= 579u) // ['Ƀ', 'ɏ']
                        {
                            if (ch <= 580u) // ['Ƀ', 'Ʉ']
                            {
                                if (ch <= 579u) // ['Ƀ', 'Ƀ']
                                {
                                    diff = -195;
                                    goto APPLY_DIFF;
                                } // ['Ƀ', 'Ƀ']
                                else if (ch >= 580u) // ['Ʉ', 'Ʉ']
                                {
                                    diff = 69;
                                    goto APPLY_DIFF;
                                } // ['Ʉ', 'Ʉ']
                            } // ['Ƀ', 'Ʉ']
                            else if (ch >= 581u) // ['Ʌ', 'ɏ']
                            {
                                if (ch <= 581u) // ['Ʌ', 'Ʌ']
                                {
                                    diff = 71;
                                    goto APPLY_DIFF;
                                } // ['Ʌ', 'Ʌ']
                                else if (ch >= 582u) // ['Ɇ', 'ɏ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ɇ', 'ɏ']
                            } // ['Ʌ', 'ɏ']
                        } // ['Ƀ', 'ɏ']
                    } // ['Ȼ', 'ɏ']
                    else if (ch >= 880u) // ['Ͱ', 'Ϗ']
                    {
                        if (ch <= 906u) // ['Ͱ', 'Ί']
                        {
                            if (ch <= 887u) // ['Ͱ', 'ͷ']
                            {
                                if (ch <= 883u) // ['Ͱ', 'ͳ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ͱ', 'ͳ']
                                else if (ch >= 886u) // ['Ͷ', 'ͷ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ͷ', 'ͷ']
                            } // ['Ͱ', 'ͷ']
                            else if (ch >= 902u) // ['Ά', 'Ί']
                            {
                                if (ch <= 902u) // ['Ά', 'Ά']
                                {
                                    diff = 38;
                                    goto APPLY_DIFF;
                                } // ['Ά', 'Ά']
                                else if (ch >= 904u) // ['Έ', 'Ί']
                                {
                                    diff = 37;
                                    goto APPLY_DIFF;
                                } // ['Έ', 'Ί']
                            } // ['Ά', 'Ί']
                        } // ['Ͱ', 'Ί']
                        else if (ch >= 908u) // ['Ό', 'Ϗ']
                        {
                            if (ch <= 911u) // ['Ό', 'Ώ']
                            {
                                if (ch <= 908u) // ['Ό', 'Ό']
                                {
                                    diff = 64;
                                    goto APPLY_DIFF;
                                } // ['Ό', 'Ό']
                                else if (ch >= 910u) // ['Ύ', 'Ώ']
                                {
                                    diff = 63;
                                    goto APPLY_DIFF;
                                } // ['Ύ', 'Ώ']
                            } // ['Ό', 'Ώ']
                            else if (ch >= 913u) // ['Α', 'Ϗ']
                            {
                                if (ch <= 929u) // ['Α', 'Ρ']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['Α', 'Ρ']
                                else if (ch >= 931u) // ['Σ', 'Ϗ']
                                {
                                    if (ch <= 939u) // ['Σ', 'Ϋ']
                                    {
                                        diff = 32;
                                        goto APPLY_DIFF;
                                    } // ['Σ', 'Ϋ']
                                    else if (ch >= 975u) // ['Ϗ', 'Ϗ']
                                    {
                                        diff = 8;
                                        goto APPLY_DIFF;
                                    } // ['Ϗ', 'Ϗ']
                                } // ['Σ', 'Ϗ']
                            } // ['Α', 'Ϗ']
                        } // ['Ό', 'Ϗ']
                    } // ['Ͱ', 'Ϗ']
                } // ['Ȼ', 'Ϗ']
            } // ['Ƴ', 'Ϗ']
        } // ['À', 'Ϗ']
        else if (ch >= 984u) // ['Ϙ', 'Ｚ']
        {
            if (ch <= 8140u) // ['Ϙ', 'ῌ']
            {
                if (ch <= 7951u) // ['Ϙ', 'Ἇ']
                {
                    if (ch <= 1153u) // ['Ϙ', 'ҁ']
                    {
                        if (ch <= 1019u) // ['Ϙ', 'ϻ']
                        {
                            if (ch <= 1016u) // ['Ϙ', 'ϸ']
                            {
                                if (ch <= 1007u) // ['Ϙ', 'ϯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ϙ', 'ϯ']
                                else if (ch >= 1015u) // ['Ϸ', 'ϸ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ϸ', 'ϸ']
                            } // ['Ϙ', 'ϸ']
                            else if (ch >= 1017u) // ['Ϲ', 'ϻ']
                            {
                                if (ch <= 1017u) // ['Ϲ', 'Ϲ']
                                {
                                    diff = -7;
                                    goto APPLY_DIFF;
                                } // ['Ϲ', 'Ϲ']
                                else if (ch >= 1018u) // ['Ϻ', 'ϻ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ϻ', 'ϻ']
                            } // ['Ϲ', 'ϻ']
                        } // ['Ϙ', 'ϻ']
                        else if (ch >= 1021u) // ['Ͻ', 'ҁ']
                        {
                            if (ch <= 1039u) // ['Ͻ', 'Џ']
                            {
                                if (ch <= 1023u) // ['Ͻ', 'Ͽ']
                                {
                                    diff = -130;
                                    goto APPLY_DIFF;
                                } // ['Ͻ', 'Ͽ']
                                else if (ch >= 1024u) // ['Ѐ', 'Џ']
                                {
                                    diff = 80;
                                    goto APPLY_DIFF;
                                } // ['Ѐ', 'Џ']
                            } // ['Ͻ', 'Џ']
                            else if (ch >= 1040u) // ['А', 'ҁ']
                            {
                                if (ch <= 1071u) // ['А', 'Я']
                                {
                                    diff = 32;
                                    goto APPLY_DIFF;
                                } // ['А', 'Я']
                                else if (ch >= 1120u) // ['Ѡ', 'ҁ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ѡ', 'ҁ']
                            } // ['А', 'ҁ']
                        } // ['Ͻ', 'ҁ']
                    } // ['Ϙ', 'ҁ']
                    else if (ch >= 1162u) // ['Ҋ', 'Ἇ']
                    {
                        if (ch <= 1315u) // ['Ҋ', 'ԣ']
                        {
                            if (ch <= 1216u) // ['Ҋ', 'Ӏ']
                            {
                                if (ch <= 1215u) // ['Ҋ', 'ҿ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ҋ', 'ҿ']
                                else if (ch >= 1216u) // ['Ӏ', 'Ӏ']
                                {
                                    diff = 15;
                                    goto APPLY_DIFF;
                                } // ['Ӏ', 'Ӏ']
                            } // ['Ҋ', 'Ӏ']
                            else if (ch >= 1217u) // ['Ӂ', 'ԣ']
                            {
                                if (ch <= 1230u) // ['Ӂ', 'ӎ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ӂ', 'ӎ']
                                else if (ch >= 1232u) // ['Ӑ', 'ԣ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ӑ', 'ԣ']
                            } // ['Ӂ', 'ԣ']
                        } // ['Ҋ', 'ԣ']
                        else if (ch >= 1329u) // ['Ա', 'Ἇ']
                        {
                            if (ch <= 4293u) // ['Ա', 'Ⴥ']
                            {
                                if (ch <= 1366u) // ['Ա', 'Ֆ']
                                {
                                    diff = 48;
                                    goto APPLY_DIFF;
                                } // ['Ա', 'Ֆ']
                                else if (ch >= 4256u) // ['Ⴀ', 'Ⴥ']
                                {
                                    diff = 7264;
                                    goto APPLY_DIFF;
                                } // ['Ⴀ', 'Ⴥ']
                            } // ['Ա', 'Ⴥ']
                            else if (ch >= 7680u) // ['Ḁ', 'Ἇ']
                            {
                                if (ch <= 7829u) // ['Ḁ', 'ẕ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ḁ', 'ẕ']
                                else if (ch >= 7840u) // ['Ạ', 'Ἇ']
                                {
                                    if (ch <= 7935u) // ['Ạ', 'ỿ']
                                    {
                                        goto UPPERCASE_IS_EVEN;
                                    } // ['Ạ', 'ỿ']
                                    else if (ch >= 7944u) // ['Ἀ', 'Ἇ']
                                    {
                                        diff = -8;
                                        goto APPLY_DIFF;
                                    } // ['Ἀ', 'Ἇ']
                                } // ['Ạ', 'Ἇ']
                            } // ['Ḁ', 'Ἇ']
                        } // ['Ա', 'Ἇ']
                    } // ['Ҋ', 'Ἇ']
                } // ['Ϙ', 'Ἇ']
                else if (ch >= 7960u) // ['Ἐ', 'ῌ']
                {
                    if (ch <= 8031u) // ['Ἐ', 'Ὗ']
                    {
                        if (ch <= 8013u) // ['Ἐ', 'Ὅ']
                        {
                            if (ch <= 7983u) // ['Ἐ', 'Ἧ']
                            {
                                if (ch <= 7965u) // ['Ἐ', 'Ἕ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ἐ', 'Ἕ']
                                else if (ch >= 7976u) // ['Ἠ', 'Ἧ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ἠ', 'Ἧ']
                            } // ['Ἐ', 'Ἧ']
                            else if (ch >= 7992u) // ['Ἰ', 'Ὅ']
                            {
                                if (ch <= 7999u) // ['Ἰ', 'Ἷ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ἰ', 'Ἷ']
                                else if (ch >= 8008u) // ['Ὀ', 'Ὅ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ὀ', 'Ὅ']
                            } // ['Ἰ', 'Ὅ']
                        } // ['Ἐ', 'Ὅ']
                        else if (ch >= 8025u) // ['Ὑ', 'Ὗ']
                        {
                            if (ch <= 8027u) // ['Ὑ', 'Ὓ']
                            {
                                if (ch <= 8025u) // ['Ὑ', 'Ὑ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ὑ', 'Ὑ']
                                else if (ch >= 8027u) // ['Ὓ', 'Ὓ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ὓ', 'Ὓ']
                            } // ['Ὑ', 'Ὓ']
                            else if (ch >= 8029u) // ['Ὕ', 'Ὗ']
                            {
                                if (ch <= 8029u) // ['Ὕ', 'Ὕ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ὕ', 'Ὕ']
                                else if (ch >= 8031u) // ['Ὗ', 'Ὗ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ὗ', 'Ὗ']
                            } // ['Ὕ', 'Ὗ']
                        } // ['Ὑ', 'Ὗ']
                    } // ['Ἐ', 'Ὗ']
                    else if (ch >= 8040u) // ['Ὠ', 'ῌ']
                    {
                        if (ch <= 8111u) // ['Ὠ', 'ᾯ']
                        {
                            if (ch <= 8079u) // ['Ὠ', 'ᾏ']
                            {
                                if (ch <= 8047u) // ['Ὠ', 'Ὧ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ὠ', 'Ὧ']
                                else if (ch >= 8072u) // ['ᾈ', 'ᾏ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾈ', 'ᾏ']
                            } // ['Ὠ', 'ᾏ']
                            else if (ch >= 8088u) // ['ᾘ', 'ᾯ']
                            {
                                if (ch <= 8095u) // ['ᾘ', 'ᾟ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾘ', 'ᾟ']
                                else if (ch >= 8104u) // ['ᾨ', 'ᾯ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['ᾨ', 'ᾯ']
                            } // ['ᾘ', 'ᾯ']
                        } // ['Ὠ', 'ᾯ']
                        else if (ch >= 8120u) // ['Ᾰ', 'ῌ']
                        {
                            if (ch <= 8123u) // ['Ᾰ', 'Ά']
                            {
                                if (ch <= 8121u) // ['Ᾰ', 'Ᾱ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ᾰ', 'Ᾱ']
                                else if (ch >= 8122u) // ['Ὰ', 'Ά']
                                {
                                    diff = -74;
                                    goto APPLY_DIFF;
                                } // ['Ὰ', 'Ά']
                            } // ['Ᾰ', 'Ά']
                            else if (ch >= 8124u) // ['ᾼ', 'ῌ']
                            {
                                if (ch <= 8124u) // ['ᾼ', 'ᾼ']
                                {
                                    diff = -9;
                                    goto APPLY_DIFF;
                                } // ['ᾼ', 'ᾼ']
                                else if (ch >= 8136u) // ['Ὲ', 'ῌ']
                                {
                                    if (ch <= 8139u) // ['Ὲ', 'Ή']
                                    {
                                        diff = -86;
                                        goto APPLY_DIFF;
                                    } // ['Ὲ', 'Ή']
                                    else if (ch >= 8140u) // ['ῌ', 'ῌ']
                                    {
                                        diff = -9;
                                        goto APPLY_DIFF;
                                    } // ['ῌ', 'ῌ']
                                } // ['Ὲ', 'ῌ']
                            } // ['ᾼ', 'ῌ']
                        } // ['Ᾰ', 'ῌ']
                    } // ['Ὠ', 'ῌ']
                } // ['Ἐ', 'ῌ']
            } // ['Ϙ', 'ῌ']
            else if (ch >= 8152u) // ['Ῐ', 'Ｚ']
            {
                if (ch <= 11364u) // ['Ῐ', 'Ɽ']
                {
                    if (ch <= 8188u) // ['Ῐ', 'ῼ']
                    {

                        if (ch <= 8171u) // ['Ῐ', 'Ύ']
                        {
                            if (ch <= 8155u) // ['Ῐ', 'Ί']
                            {
                                if (ch <= 8153u) // ['Ῐ', 'Ῑ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ῐ', 'Ῑ']
                                else if (ch >= 8154u) // ['Ὶ', 'Ί']
                                {
                                    diff = -100;
                                    goto APPLY_DIFF;
                                } // ['Ὶ', 'Ί']
                            } // ['Ῐ', 'Ί']
                            else if (ch >= 8168u) // ['Ῠ', 'Ύ']
                            {
                                if (ch <= 8169u) // ['Ῠ', 'Ῡ']
                                {
                                    diff = -8;
                                    goto APPLY_DIFF;
                                } // ['Ῠ', 'Ῡ']
                                else if (ch >= 8170u) // ['Ὺ', 'Ύ']
                                {
                                    diff = -112;
                                    goto APPLY_DIFF;
                                } // ['Ὺ', 'Ύ']
                            } // ['Ῠ', 'Ύ']
                        } // ['Ῐ', 'Ύ']
                        else if (ch >= 8172u) // ['Ῥ', 'ῼ']
                        {
                            if (ch <= 8185u) // ['Ῥ', 'Ό']
                            {
                                if (ch <= 8172u) // ['Ῥ', 'Ῥ']
                                {
                                    diff = -7;
                                    goto APPLY_DIFF;
                                } // ['Ῥ', 'Ῥ']
                                else if (ch >= 8184u) // ['Ὸ', 'Ό']
                                {
                                    diff = -128;
                                    goto APPLY_DIFF;
                                } // ['Ὸ', 'Ό']
                            } // ['Ῥ', 'Ό']
                            else if (ch >= 8186u) // ['Ὼ', 'ῼ']
                            {
                                if (ch <= 8187u) // ['Ὼ', 'Ώ']
                                {
                                    diff = -126;
                                    goto APPLY_DIFF;
                                } // ['Ὼ', 'Ώ']
                                else if (ch >= 8188u) // ['ῼ', 'ῼ']
                                {
                                    diff = -9;
                                    goto APPLY_DIFF;
                                } // ['ῼ', 'ῼ']
                            } // ['Ὼ', 'ῼ']
                        } // ['Ῥ', 'ῼ']
                    } // ['Ῐ', 'ῼ']
                    else if (ch >= 8498u) // ['Ⅎ', 'Ɽ']
                    {
                        if (ch <= 9423u) // ['Ⅎ', 'Ⓩ']
                        {
                            if (ch <= 8559u) // ['Ⅎ', 'Ⅿ']
                            {
                                if (ch <= 8498u) // ['Ⅎ', 'Ⅎ']
                                {
                                    diff = 28;
                                    goto APPLY_DIFF;
                                } // ['Ⅎ', 'Ⅎ']
                                else if (ch >= 8544u) // ['Ⅰ', 'Ⅿ']
                                {
                                    diff = 16;
                                    goto APPLY_DIFF;
                                } // ['Ⅰ', 'Ⅿ']
                            } // ['Ⅎ', 'Ⅿ']
                            else if (ch >= 8579u) // ['Ↄ', 'Ⓩ']
                            {
                                if (ch <= 8580u) // ['Ↄ', 'ↄ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ↄ', 'ↄ']
                                else if (ch >= 9398u) // ['Ⓐ', 'Ⓩ']
                                {
                                    diff = 26;
                                    goto APPLY_DIFF;
                                } // ['Ⓐ', 'Ⓩ']
                            } // ['Ↄ', 'Ⓩ']
                        } // ['Ⅎ', 'Ⓩ']
                        else if (ch >= 11264u) // ['Ⰰ', 'Ɽ']
                        {
                            if (ch <= 11361u) // ['Ⰰ', 'ⱡ']
                            {
                                if (ch <= 11310u) // ['Ⰰ', 'Ⱞ']
                                {
                                    diff = 48;
                                    goto APPLY_DIFF;
                                } // ['Ⰰ', 'Ⱞ']
                                else if (ch >= 11360u) // ['Ⱡ', 'ⱡ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ⱡ', 'ⱡ']
                            } // ['Ⰰ', 'ⱡ']
                            else if (ch >= 11362u) // ['Ɫ', 'Ɽ']
                            {
                                if (ch <= 11362u) // ['Ɫ', 'Ɫ']
                                {
                                    diff = -10743;
                                    goto APPLY_DIFF;
                                } // ['Ɫ', 'Ɫ']
                                else if (ch >= 11363u) // ['Ᵽ', 'Ɽ']
                                {
                                    if (ch <= 11363u) // ['Ᵽ', 'Ᵽ']
                                    {
                                        diff = -3814;
                                        goto APPLY_DIFF;
                                    } // ['Ᵽ', 'Ᵽ']
                                    else if (ch >= 11364u) // ['Ɽ', 'Ɽ']
                                    {
                                        diff = -10727;
                                        goto APPLY_DIFF;
                                    } // ['Ɽ', 'Ɽ']
                                } // ['Ᵽ', 'Ɽ']
                            } // ['Ɫ', 'Ɽ']
                        } // ['Ⰰ', 'Ɽ']
                    } // ['Ⅎ', 'Ɽ']
                } // ['Ῐ', 'Ɽ']
                else if (ch >= 11367u) // ['Ⱨ', 'Ｚ']
                {
                    if (ch <= 42591u) // ['Ⱨ', 'ꙟ']
                    {
                        if (ch <= 11375u) // ['Ⱨ', 'Ɐ']
                        {
                            if (ch <= 11373u) // ['Ⱨ', 'Ɑ']
                            {
                                if (ch <= 11372u) // ['Ⱨ', 'ⱬ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ⱨ', 'ⱬ']
                                else if (ch >= 11373u) // ['Ɑ', 'Ɑ']
                                {
                                    diff = -10780;
                                    goto APPLY_DIFF;
                                } // ['Ɑ', 'Ɑ']
                            } // ['Ⱨ', 'Ɑ']
                            else if (ch >= 11374u) // ['Ɱ', 'Ɐ']
                            {
                                if (ch <= 11374u) // ['Ɱ', 'Ɱ']
                                {
                                    diff = -10749;
                                    goto APPLY_DIFF;
                                } // ['Ɱ', 'Ɱ']
                                else if (ch >= 11375u) // ['Ɐ', 'Ɐ']
                                {
                                    diff = -10783;
                                    goto APPLY_DIFF;
                                } // ['Ɐ', 'Ɐ']
                            } // ['Ɱ', 'Ɐ']
                        } // ['Ⱨ', 'Ɐ']
                        else if (ch >= 11378u) // ['Ⱳ', 'ꙟ']
                        {
                            if (ch <= 11382u) // ['Ⱳ', 'ⱶ']
                            {
                                if (ch <= 11379u) // ['Ⱳ', 'ⱳ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ⱳ', 'ⱳ']
                                else if (ch >= 11381u) // ['Ⱶ', 'ⱶ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ⱶ', 'ⱶ']
                            } // ['Ⱳ', 'ⱶ']
                            else if (ch >= 11392u) // ['Ⲁ', 'ꙟ']
                            {
                                if (ch <= 11491u) // ['Ⲁ', 'ⳣ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ⲁ', 'ⳣ']
                                else if (ch >= 42560u) // ['Ꙁ', 'ꙟ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꙁ', 'ꙟ']
                            } // ['Ⲁ', 'ꙟ']
                        } // ['Ⱳ', 'ꙟ']
                    } // ['Ⱨ', 'ꙟ']
                    else if (ch >= 42594u) // ['Ꙣ', 'Ｚ']
                    {
                        if (ch <= 42863u) // ['Ꙣ', 'ꝯ']
                        {
                            if (ch <= 42647u) // ['Ꙣ', 'ꚗ']
                            {
                                if (ch <= 42605u) // ['Ꙣ', 'ꙭ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꙣ', 'ꙭ']
                                else if (ch >= 42624u) // ['Ꚁ', 'ꚗ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꚁ', 'ꚗ']
                            } // ['Ꙣ', 'ꚗ']
                            else if (ch >= 42786u) // ['Ꜣ', 'ꝯ']
                            {
                                if (ch <= 42799u) // ['Ꜣ', 'ꜯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꜣ', 'ꜯ']
                                else if (ch >= 42802u) // ['Ꜳ', 'ꝯ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꜳ', 'ꝯ']
                            } // ['Ꜣ', 'ꝯ']
                        } // ['Ꙣ', 'ꝯ']
                        else if (ch >= 42873u) // ['Ꝺ', 'Ｚ']
                        {
                            if (ch <= 42877u) // ['Ꝺ', 'Ᵹ']
                            {
                                if (ch <= 42876u) // ['Ꝺ', 'ꝼ']
                                {
                                    goto UPPERCASE_IS_ODD;
                                } // ['Ꝺ', 'ꝼ']
                                else if (ch >= 42877u) // ['Ᵹ', 'Ᵹ']
                                {
                                    diff = -35332;
                                    goto APPLY_DIFF;
                                } // ['Ᵹ', 'Ᵹ']
                            } // ['Ꝺ', 'Ᵹ']
                            else if (ch >= 42878u) // ['Ꝿ', 'Ｚ']
                            {
                                if (ch <= 42887u) // ['Ꝿ', 'ꞇ']
                                {
                                    goto UPPERCASE_IS_EVEN;
                                } // ['Ꝿ', 'ꞇ']
                                else if (ch >= 42891u) // ['Ꞌ', 'Ｚ']
                                {
                                    if (ch <= 42892u) // ['Ꞌ', 'ꞌ']
                                    {
                                        goto UPPERCASE_IS_ODD;
                                    } // ['Ꞌ', 'ꞌ']
                                    else if (ch >= 65313u) // ['Ａ', 'Ｚ']
                                    {
                                        diff = 32;
                                        goto APPLY_DIFF;
                                    } // ['Ａ', 'Ｚ']
                                } // ['Ꞌ', 'Ｚ']
                            } // ['Ꝿ', 'Ｚ']
                        } // ['Ꝺ', 'Ｚ']
                    } // ['Ꙣ', 'Ｚ']
                } // ['Ⱨ', 'Ｚ']
            } // ['Ῐ', 'Ｚ']
        } // ['Ϙ', 'Ｚ']
    }


    // no change
    return ch;

    APPLY_DIFF:
    return (char32_t)(ch + diff);

    UPPERCASE_IS_EVEN:
    return (char32_t)(ch | 1u);

    UPPERCASE_IS_ODD:
    return (char32_t)((ch + 1) & ~1u);
}

